# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ecd8e0384f4d886a28549fd456b1890bbb0c91a97bd88d61bab0d1058d09cd0a1e02af2dc74345622230eb6cba7b489c49e138b4d90c28768232a0c8adba80

test:
  secret_key_base: 2bb1f36deaa4ab1bb01e2eedb14bdea415d698687234af895baef5bb43ccff4cebe3f46dcc6a39c85716416b47a38f5cf8a43cf28cebb766e7f4a14550978cc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
